name: rust-http-cli
version: git
summary: A user-friendly command-line tool to request HTTP APis
description: |
  Rust HTTP Cli (`rh`) is a user-friendly, lightweight and performant command-line tool to request HTTP APis.
  You can debug, test and verify any HTTP APi with rh in a simple and efficient way.
  `rh` is focused on performance and stability.
  You don't need OpenSSL because `rh` is based on Rustls, a modern TLS library alternative to OpenSSL.

  `rh` is a standalone application with no runtime or garbage collector, so it doesn't require Python or Java installed on your machine for example.
  `rh` is based on Rust that is a blazing fast and memory-efficient language.
license: MIT

base: core18
confinement: strict
grade: stable
compression: lzo

parts:
  rust-http-cli:
    plugin: rust
    source: https://github.com/twigly/rust-http-cli.git

apps:
  rust-http-cli:
    command: bin/rh
