name: CD Crates

on:
  create:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+*'

jobs:
  publish_crates:
    name: Publish to crates.io
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: katyo/publish-crates@v1
        with:
          registry-token: ${{ secrets.CARGO_REGISTRY_TOKEN }}
