name: CI

on:
  push:
    paths:
      - '**.rs'

env:
  CARGO_TERM_COLOR: always

jobs:
  tests:
    name: ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        rust: [stable]
    steps:
    - uses: actions/checkout@v2
    - name: Lint
      if: matrix.os == 'ubuntu-latest'
      run: cargo clippy -- -D warnings
    - name: Build
      run: cargo build --verbose
    - name: Unit tests
      run: cargo test --verbose
