name: Publish

on:
  workflow_run:
    workflows: [CD]
    types:
      - completed

env:
  CARGO_TERM_COLOR: always

jobs:
  on-failure:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'failure' }}
    steps:
      - run: echo 'The triggering workflow failed'
      - run: exit 100
      
  crates:
    name: Crates.io
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Publish
        env:
          CARGO_REGISTRY_TOKEN: ${{ secrets.CARGO_REGISTRY_TOKEN }}
        run: cargo publish --package rh


# name: Publish

# on:
#   push:
#     paths:
#       - '**.yml'

# jobs:
#   publish_crates:
#     name: Publish to crates.io
#     runs-on: ubuntu-latest
#     steps:
#       - name: Checkout
#         uses: actions/checkout@v2

#       - name: Publish
#         env:
#           CARGO_REGISTRY_TOKEN: ${{ secrets.CARGO_REGISTRY_TOKEN }}
#         run: cargo publish --package rh
